// Book achievements are intentionally separate from the screen-media catalog.
const badge = (id, name, description, rule, target = 1, options = {}) => ({
  id, name, description, rule, target, category: options.category ?? 'Reading milestones',
  rarity: options.rarity ?? 'Common', media: 'book', availability: 'active',
})

export const BOOK_ACHIEVEMENTS = [
  badge('book-first-chapter', 'First Chapter', 'Finish your first book.', 'book_count'),
  badge('book-getting-started', 'Getting Started', 'Finish 5 books.', 'book_count', 5),
  badge('book-bookworm', 'Bookworm', 'Finish 10 books.', 'book_count', 10),
  badge('book-dedicated-reader', 'Dedicated Reader', 'Finish 25 books.', 'book_count', 25, { rarity: 'Uncommon' }),
  badge('book-library-regular', 'Library Regular', 'Finish 50 books.', 'book_count', 50, { rarity: 'Rare' }),
  badge('book-century-club', 'Century Club', 'Finish 100 books.', 'book_count', 100, { rarity: 'Epic' }),
  badge('book-page-turner', 'Page Turner', 'Read 1,000 pages.', 'pages_read', 1000),
  badge('book-paper-mountain', 'Paper Mountain', 'Read 5,000 pages.', 'pages_read', 5000, { rarity: 'Uncommon' }),
  badge('book-page-conqueror', 'Page Conqueror', 'Read 10,000 pages.', 'pages_read', 10000, { rarity: 'Rare' }),
  badge('book-back-to-back', 'Back-to-Back Books', 'Finish 2 books within 7 days.', 'back_to_back', 2),
  badge('book-four-season-reader', 'Four-Season Reader', 'Finish at least one book in every season.', 'seasons', 4),
  badge('book-format-explorer', 'Format Explorer', 'Finish a print book, an e-book, and an audiobook.', 'formats', 3),
  badge('book-five-star-find', 'Five-Star Find', 'Rate a book 5 stars.', 'five_star_rating'),
  badge('book-first-favorite', 'First Favorite', 'Save your first book as a favorite.', 'flag:favorite'),
  badge('book-translated-treasure', 'Translated Treasure', 'Finish a translated book.', 'flag:translated'),
  badge('book-decade-hopper', 'Decade Hopper', 'Read books published in 5 different decades.', 'decades', 5),
  badge('book-genre-explorer', 'Genre Explorer', 'Read books from 5 different genres.', 'genres', 5),
  badge('book-genre-adventurer', 'Genre Adventurer', 'Read books from 10 different genres.', 'genres', 10, { rarity: 'Rare' }),
  badge('book-author-discovery', 'Author Discovery', 'Read a book by a new-to-you author.', 'flag:newAuthor'),
  badge('book-author-devotee', 'Author Devotee', 'Read 5 books by the same author.', 'author_max', 5),
  badge('book-series-starter', 'Series Starter', 'Begin a book series.', 'flag:seriesStarted'),
  badge('book-series-finisher', 'Series Finisher', 'Complete an entire series.', 'flag:seriesFinished'),
  badge('book-backlist-explorer', 'Backlist Explorer', 'Read a book published more than 20 years ago.', 'backlist'),
  badge('book-fresh-release', 'Fresh Release', 'Read a book in the year it was published.', 'fresh_release'),
  badge('book-classic-reader', 'Classic Reader', 'Finish a recognized classic.', 'flag:classic'),
  badge('book-big-book-energy', 'Big Book Energy', 'Finish a book longer than 500 pages.', 'long_book'),
  badge('book-epic-reader', 'Epic Reader', 'Finish a book longer than 800 pages.', 'epic_book'),
  badge('book-quick-read', 'Quick Read', 'Finish a book under 150 pages.', 'short_book'),
  badge('book-audiobook-listener', 'Audiobook Listener', 'Finish your first audiobook.', 'format:audiobook'),
  badge('book-ebook-explorer', 'E-book Explorer', 'Finish your first e-book.', 'format:ebook'),
  badge('book-library-supporter', 'Library Supporter', 'Finish a book borrowed from a library.', 'flag:library'),
  badge('book-recommendation-accepted', 'Recommendation Accepted', 'Finish a recommended book.', 'flag:recommended'),
  badge('book-comfort-reread', 'Comfort Reread', 'Reread a favorite book.', 'reread'),
  badge('book-tbr-progress', 'TBR Progress', 'Finish 5 books from your TBR.', 'tbr_completed', 5),
  badge('book-tbr-hero', 'TBR Hero', 'Finish 20 books from your TBR.', 'tbr_completed', 20, { rarity: 'Rare' }),
  badge('book-plot-twist-victim', 'Plot Twist Victim', 'Record a book whose twist surprised you.', 'flag:plotTwist', 1, { category: 'Fun & quirky' }),
  badge('book-emotional-damage', 'Emotional Damage', 'Finish a book that made you cry.', 'flag:madeCry', 1, { category: 'Fun & quirky' }),
  badge('book-laughing-in-public', 'Laughing in Public', 'Read a book that made you laugh aloud.', 'flag:madeLaugh', 1, { category: 'Fun & quirky' }),
  badge('book-fictional-crush', 'Fictional Crush', 'Save a character as a favorite.', 'flag:fictionalCrush', 1, { category: 'Fun & quirky' }),
  badge('book-found-family-fan', 'Found Family Fan', 'Read a book featuring a found-family theme.', 'flag:foundFamily', 1, { category: 'Fun & quirky' }),
  badge('book-villain-apologist', 'Villain Apologist', 'Choose the villain as a favorite character.', 'flag:villainFavorite', 1, { category: 'Fun & quirky' }),
  badge('book-enemies-to-lovers', 'Enemies to Lovers', 'Finish an enemies-to-lovers book.', 'flag:enemiesToLovers', 1, { category: 'Fun & quirky' }),
  badge('book-slow-burn-survivor', 'Slow Burn Survivor', 'Finish a slow-burn romance.', 'flag:slowBurn', 1, { category: 'Fun & quirky' }),
  badge('book-cozy-corner', 'Cozy Corner', 'Finish a cozy book.', 'flag:cozy', 1, { category: 'Fun & quirky' }),
  badge('book-summer-escape', 'Summer Escape', 'Finish a book while on vacation.', 'flag:vacation', 1, { category: 'Fun & quirky' }),
  badge('book-cover-judge', 'Cover Judge', 'Pick a book because of its cover and enjoy it.', 'flag:coverEnjoyed', 1, { category: 'Fun & quirky' }),
  badge('book-cover-betrayal', 'Cover Betrayal', 'Pick a book because of its cover and regret it.', 'flag:coverRegretted', 1, { category: 'Fun & quirky' }),
  badge('book-hype-train', 'Hype Train', 'Read a trending or recommended book.', 'flag:hyped', 1, { category: 'Fun & quirky' }),
  badge('book-dnf-with-confidence', 'DNF With Confidence', 'Record a book you stopped reading.', 'flag:dnf', 1, { category: 'Fun & quirky' }),
  badge('book-mood-reader', 'Mood Reader', 'Start a different book for your mood.', 'flag:moodRead', 1, { category: 'Fun & quirky' }),
  badge('book-adaptation-check', 'Adaptation Check', 'Read a book and watch its adaptation.', 'flag:adaptationWatched', 1, { category: 'Fun & quirky' }),
  badge('book-book-was-better', 'The Book Was Better', 'Prefer the book over its adaptation.', 'flag:bookWasBetter', 1, { category: 'Fun & quirky' }),
  badge('book-rare-adaptation-win', 'Rare Adaptation Win', 'Prefer the adaptation over its book.', 'flag:adaptationWon', 1, { category: 'Fun & quirky' }),
  badge('book-map-needed', 'Map Needed', 'Read a fantasy book with a map.', 'flag:mapUsed', 1, { category: 'Fun & quirky' }),
  badge('book-name-pronunciation-crisis', 'Name Pronunciation Crisis', 'Read a book with a tricky name.', 'flag:trickyNames', 1, { category: 'Fun & quirky' }),
  badge('book-trope-collector', 'Trope Collector', 'Read books featuring 10 different tropes.', 'tropes', 10, { category: 'Fun & quirky', rarity: 'Rare' }),
  badge('book-five-star-streak', 'Five-Star Streak', 'Rate 3 books in a row 5 stars.', 'five_star_streak', 3, { category: 'Fun & quirky' }),
  badge('book-reading-slump-escape', 'Reading Slump Escape', 'Finish a book after a reading slump.', 'flag:slumpEscape', 1, { category: 'Fun & quirky' }),
]
