// Pair achievements are deliberately data-driven. A session can record any of
// these moments; objective milestones are additionally calculated from history.
const groups = [
  ['First Milestones', 'Better Together|Pilot Partners|The Beginning of a Binge|Movie Night Official|Same Screen, Same Story'],
  ['Movies Watched Together', 'Double Feature|Movie Night Regulars|Perfect Pairing|Cinema Companions|Dynamic Duo|Reel Soulmates|Feature-Length Friendship|Weekend Marathon|Around the Clock'],
  ['TV Shows and Episodes', 'One More Episode|Binge Buddies|Season Starters|Season Survivors|From Pilot to Finale|Series Commitment|Long-Term Relationship|Episode Experts|Binge Legends|No Episode Left Behind'],
  ['Shared Consistency', 'Weekly Tradition|Watch Streak|Unbreakable Streak|Monthly Ritual|Year of Stories|Friday Night Crew|Sunday Series Club|Always in Sync'],
  ['Genre Exploration', 'Comedy Couple|Thrill Seekers|Brave Together|Mystery Partners|Sci-Fi Sidekicks|Fantasy Fellowship|Romance Mode|Action Alliance|Documentary Duo|Genre Tourists|Mood Swing|Out of Our Comfort Zone'],
  ['Choosing What to Watch', 'Your Pick|My Pick|Fair and Square|Decision Made|Perfect Match|No Arguments Tonight|The Negotiators|Watchlist Winner|Finally Watching It|Random Choice|Mood Match'],
  ['Ratings and Reactions', 'Same Taste|Almost Identical|We Need to Talk|Perfect Ten Together|Shared Disappointment|Unexpected Favourite|Rating Twins|Different Worlds|Consensus Critics|Balanced Opinions|Review Partners'],
  ['Characters and Favourites', 'Same Favourite|Character Rivals|Opposites Attract|Main Character Energy|Villain Appreciation Club|Supporting Cast Supremacy|Character Experts|Perfectly Cast|Team A vs Team B'],
  ['Quizzes and Predictions', 'Quiz Night|Telepathic|Know Your Partner|Character Match|Opposite Characters|Plot Detective|Called It!|No Spoilers, Just Skills|Quiz Champions|Competitive Viewing|Perfect Score|Shared Genius'],
  ['Timing and Special Occasions', 'Late-Night Watchers|Early Screening|New Year, New Story|Birthday Pick|Anniversary Screening|Holiday Marathon|Rainy Day Cinema|Spooky Season|Summer Blockbusters|Award Season'],
  ['Fun and Unusual', "Snack Synchronised|Remote but Together|Couch Critics|Credits Crew|Post-Credit Hunters|The Rewatch Pact|Their Favourite, My First Time|Comfort Watch|So Bad It's Good|Plot Hole Inspectors|Quote Machine|Emotional Damage|Worth the Hype|Hidden Gem Hunters|No Phones Allowed|The Great Compromise|Watch Together Legends"],
  ['Secret Achievements', 'Are You Still Watching?|Just One More... Again|We Watched That?|Accidental Marathon|The Silent Agreement|Impossible Agreement|Shared Universe|Completionists|No Context Needed|Plot Twist Victims|Relationship Test Passed'],
]

const slug = (name) => name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '')
const targets = new Map([
  ['Movie Night Regulars', 5], ['Perfect Pairing', 10], ['Cinema Companions', 25], ['Dynamic Duo', 50], ['Reel Soulmates', 100], ['Long-Term Relationship', 100], ['Episode Experts', 250], ['Binge Legends', 500], ['Watch Streak', 3], ['Unbreakable Streak', 7], ['Weekly Tradition', 4], ['Friday Night Crew', 5], ['Sunday Series Club', 5], ['Genre Tourists', 10], ['Rating Twins', 5], ['Different Worlds', 5], ['Consensus Critics', 10], ['Balanced Opinions', 25], ['Character Experts', 10], ['Quiz Champions', 10], ['Competitive Viewing', 5], ['No Spoilers, Just Skills', 5], ['Watch Together Legends', 25], ['Comfort Watch', 3], ['Post-Credit Hunters', 5], ['Shared Universe', 5],
])

const descriptions = new Map([
  ['Better Together', 'Watch your first movie together.'], ['Pilot Partners', 'Watch the first episode of a show together.'], ['The Beginning of a Binge', 'Start your first TV series together.'], ['Movie Night Official', 'Complete your first shared watch session.'], ['Same Screen, Same Story', 'Finish the same title on the same day.'],
  ['Double Feature', 'Watch 2 movies together in one day.'], ['Movie Night Regulars', 'Watch 5 movies together.'], ['Perfect Pairing', 'Watch 10 movies together.'], ['Cinema Companions', 'Watch 25 movies together.'], ['Dynamic Duo', 'Watch 50 movies together.'], ['Reel Soulmates', 'Watch 100 movies together.'], ['Feature-Length Friendship', 'Spend 100 hours watching movies together.'], ['Weekend Marathon', 'Watch 3 movies together during one weekend.'], ['Around the Clock', 'Watch movies together in the morning, afternoon, and evening.'],
  ['One More Episode', 'Watch 3 episodes together in one session.'], ['Binge Buddies', 'Watch 5 episodes together in one day.'], ['Season Starters', 'Begin a season together.'], ['Season Survivors', 'Finish an entire season together.'], ['From Pilot to Finale', 'Watch every episode of a show together.'], ['Series Commitment', 'Complete a show with at least 3 seasons together.'], ['Long-Term Relationship', 'Watch 100 episodes together.'], ['Episode Experts', 'Watch 250 episodes together.'], ['Binge Legends', 'Watch 500 episodes together.'], ['No Episode Left Behind', 'Never watch an episode separately during an entire season.'],
  ['Weekly Tradition', 'Watch something together once a week for 4 weeks.'], ['Watch Streak', 'Watch together for 3 consecutive days.'], ['Unbreakable Streak', 'Watch together for 7 consecutive days.'], ['Monthly Ritual', 'Have at least one shared watch session every month for 6 months.'], ['Year of Stories', 'Watch something together in every month of the year.'], ['Friday Night Crew', 'Watch together on 5 Fridays.'], ['Sunday Series Club', 'Watch TV episodes together on 5 Sundays.'], ['Always in Sync', 'Complete 10 planned watch sessions without missing one.'],
  ['Comedy Couple', 'Watch 10 comedies together.'], ['Thrill Seekers', 'Watch 10 thrillers together.'], ['Brave Together', 'Watch 10 horror movies or episodes together.'], ['Mystery Partners', 'Watch 10 mysteries together.'], ['Sci-Fi Sidekicks', 'Watch 10 science-fiction titles together.'], ['Fantasy Fellowship', 'Watch 10 fantasy titles together.'], ['Romance Mode', 'Watch 10 romance titles together.'], ['Action Alliance', 'Watch 10 action titles together.'], ['Documentary Duo', 'Watch 10 documentaries together.'], ['Genre Tourists', 'Watch titles from 10 different genres together.'], ['Mood Swing', 'Watch 5 different genres during one week.'], ['Out of Our Comfort Zone', 'Finish a title from a genre neither person normally chooses.'],
  ['Your Pick', 'Watch a title chosen entirely by your partner.'], ['My Pick', 'Have your partner watch one of your selections.'], ['Fair and Square', 'Alternate who chooses the title for 10 sessions.'], ['Decision Made', 'Select a title from a shared shortlist.'], ['Perfect Match', 'Both independently choose the same title.'], ['No Arguments Tonight', 'Agree on a title with the first suggestion.'], ['The Negotiators', 'Choose a title after comparing at least 5 options.'], ['Watchlist Winner', 'Watch a title that has been on your shared list for 30 days.'], ['Finally Watching It', 'Complete the oldest title on your shared watchlist.'], ['Random Choice', "Watch a title selected by the app's random picker."], ['Mood Match', "Watch a title recommended from both users' selected moods."],
  ['Same Taste', 'Give a title the exact same rating.'], ['Almost Identical', 'Give ratings within 0.5 points of each other.'], ['We Need to Talk', 'Give ratings that differ by at least 4 points.'], ['Perfect Ten Together', 'Both give the same title the highest possible rating.'], ['Shared Disappointment', 'Both rate a title below 3 out of 10.'], ['Unexpected Favourite', 'Both rate a randomly selected title highly.'], ['Rating Twins', 'Match ratings on 5 titles.'], ['Different Worlds', 'Disagree strongly on 5 titles.'], ['Consensus Critics', 'Match ratings on 10 titles.'], ['Balanced Opinions', 'Complete 25 titles where both users submitted ratings.'], ['Review Partners', 'Both leave a reaction or review for the same title.'],
  ['Same Favourite', 'Choose the same favourite character.'], ['Character Rivals', 'Choose rival characters as your favourites.'], ['Opposites Attract', 'Choose completely different favourite characters.'], ['Main Character Energy', 'Both choose the protagonist.'], ['Villain Appreciation Club', 'Both choose the villain.'], ['Supporting Cast Supremacy', 'Neither person chooses the main character.'], ['Character Experts', 'Complete favourite-character selections for 10 titles.'], ['Perfectly Cast', 'Agree on the best-performing actor.'], ['Team A vs Team B', "Choose opposite sides in a show's central conflict."],
  ['Quiz Night', 'Complete your first shared quiz.'], ['Telepathic', 'Give the same answer to every question in a quiz.'], ['Know Your Partner', "Correctly predict your partner's answers."], ['Character Match', 'Receive the same character result in a personality quiz.'], ['Opposite Characters', 'Receive completely opposite character results.'], ['Plot Detective', 'Correctly predict the ending.'], ['Called It!', 'Correctly predict a major plot twist.'], ['No Spoilers, Just Skills', 'Make 5 correct episode predictions.'], ['Quiz Champions', 'Complete 10 shared quizzes.'], ['Competitive Viewing', 'Win 5 quizzes against your partner.'], ['Perfect Score', 'Get every question correct in a shared quiz.'], ['Shared Genius', 'Both achieve a perfect quiz score.'],
  ['Late-Night Watchers', 'Finish a title after midnight.'], ['Early Screening', 'Start watching before 9:00 AM.'], ['New Year, New Story', "Watch something together on New Year's Day."], ['Birthday Pick', 'Watch a title selected by the birthday person.'], ['Anniversary Screening', 'Complete a shared title on your anniversary.'], ['Holiday Marathon', 'Watch 3 holiday-themed titles together.'], ['Rainy Day Cinema', 'Watch 3 titles during one rainy weekend.'], ['Spooky Season', 'Watch 5 horror titles together in October.'], ['Summer Blockbusters', 'Watch 5 action or adventure movies during summer.'], ['Award Season', 'Watch 5 major award-winning or nominated titles together.'],
  ['Snack Synchronised', 'Select the same movie-night snack.'], ['Remote but Together', 'Complete a shared session while watching from different locations.'], ['Couch Critics', 'Pause a title at least 10 times to discuss it.'], ['Credits Crew', 'Stay until the end of the credits.'], ['Post-Credit Hunters', 'Discover 5 post-credit scenes together.'], ['The Rewatch Pact', 'Rewatch a title that both users love.'], ['Their Favourite, My First Time', "Watch your partner's favourite movie for the first time."], ['Comfort Watch', 'Rewatch the same title together 3 times.'], ['So Bad It\'s Good', 'Finish a poorly rated title and both admit you enjoyed it.'], ['Plot Hole Inspectors', 'Both flag the same plot hole.'], ['Quote Machine', 'Save or submit the same favourite quote.'], ['Emotional Damage', 'Both mark the same title as emotionally devastating.'], ['Worth the Hype', 'Both highly rate a popular title you had postponed.'], ['Hidden Gem Hunters', 'Both highly rate a lesser-known title.'], ['No Phones Allowed', 'Complete a distraction-free watch session.'], ['The Great Compromise', "Watch one person's movie choice followed by the other's."], ['Watch Together Legends', 'Unlock 25 Watch Together achievements.'],
  ['Are You Still Watching?', 'Watch for more than 6 hours in one day.'], ['Just One More... Again', 'Continue watching after agreeing to stop.'], ['We Watched That?', 'Both give a low confidence score when recalling the plot.'], ['Accidental Marathon', 'Watch at least 5 episodes without planning a binge.'], ['The Silent Agreement', "Both rate a title before seeing the other person's rating and choose the same score."], ['Impossible Agreement', 'Match the title, rating, favourite character, and favourite scene.'], ['Shared Universe', 'Watch 5 connected movies or shows from the same franchise.'], ['Completionists', 'Watch every title in a movie franchise together.'], ['No Context Needed', 'Start a sequel without either person watching the previous title.'], ['Plot Twist Victims', 'Both submit an incorrect prediction immediately before a reveal.'], ['Relationship Test Passed', 'Finish a title despite having completely opposite opinions about it.'],
])

export const WATCH_TOGETHER_ACHIEVEMENTS = groups.flatMap(([category, text]) => text.split('|').map((name) => ({
  id: `watch-together-${slug(name)}`,
  name,
  description: descriptions.get(name) || `Complete the shared moment: ${name}.`,
  category,
  rule: `session:${slug(name)}`,
  target: targets.get(name) ?? 1,
  availability: 'active',
  rarity: category === 'Secret Achievements' ? 'Rare' : 'Common',
  media: 'watch_together',
  secret: category === 'Secret Achievements',
})))

export const WATCH_TOGETHER_ACHIEVEMENT_BY_ID = new Map(WATCH_TOGETHER_ACHIEVEMENTS.map((item) => [item.id, item]))
